Vagrant.configure("2") do |config|
  # see the online documentation at https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu/trusty64"

  # Port forward notebooks port to host machine
  config.vm.network :forwarded_port, guest: 8675, host: 8675

  # Provision using ansible local
  config.vm.provision "ansible_local" do |ansible|
		  ansible.verbose = "v"
		  ansible.playbook = "devbox.yml"
  end
  
  config.vm.define :devbox do |t| end
  
  # Configure virtualbox to have 4gb ram and 4cpus
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 8192
    vb.cpus = 4
  end

end
