# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # see the online documentation at https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu/trusty64"

  # Port forward notebooks port to host machine
  config.vm.network :forwarded_port, guest: 8888, host: 8675

  # Provision using ansible
  config.vm.provision "ansible_local" do |ansible|
		  ansible.verbose = "v"
		  ansible.playbook = "devbox.yml"
  end
end
