USER_NAMES = ['Alex',
			  'Tomer',
			  'Matt',
			  'Rachel',
			  'Sam',
			  'Joey']

PRODUCT_NAMES = ['The Shawshank Redemption',
				 'The Godfather',
				 'The Dark Knight',
				 'Pulp Fiction',
				 'Fight Club',
				 'Forrest Gump',
				 'Inception',
				 'Goodfellas',
				 'The Matrix',
				 'The Silence of the Lambs',
				 'Spirited Away',
				 'Interstellar',
				 'Raiders of the Lost Ark',
				 'Back to the Future',
				 'Logan',
				 'The Lion King',
				 'WALL-E',
				 'American Beauty',
				 'The Dark Knight Rises',
				 'Princess Mononoke']

POSSIBLE_PRICES = [6.98, 10.99, 11.99, 15.99, 20.00]

MOVIES_WATCHED = {'Alex': ['The Shawshank Redemption',
							'The Dark Knight',
							'Pulp Fiction',
							'Fight Club',
							'Forrest Gump',
							'Inception',
							'The Matrix',
							'Spirited Away',
							'Interstellar',
							'Raiders of the Lost Ark',
							'Back to the Future',
							'The Lion King',
							'WALL-E',
							'American Beauty',
							'The Dark Knight Rises',
							'Princess Mononoke'],
					'Tomer': ['The Shawshank Redemption',
							'The Dark Knight',
							'Fight Club',
							'Forrest Gump',
							'Inception',
							'The Matrix',
							'The Silence of the Lambs',
							'Raiders of the Lost Ark',
							'Back to the Future',
							'The Lion King',
							'WALL-E',
							'The Dark Knight Rises'],
				  'Matt': ['Forrest Gump',
						   'Spirited Away',
						   'The Lion King',
						   'WALL-E',
						   'Princess Mononoke'],
				  'Rachel': ['The Godfather',
							 'The Dark Knight',
							 'Pulp Fiction',
							 'Fight Club',
							 'Forrest Gump',
							 'Inception',
							 'The Matrix',
							 'The Silence of the Lambs',
							 'Spirited Away',
							 'Interstellar',
							 'Raiders of the Lost Ark',
							 'Back to the Future',
							 'The Lion King',
							 'WALL-E',
							 'American Beauty',
							 'The Dark Knight Rises'],
				  'Sam': ['The Shawshank Redemption',
						  'Forrest Gump',
						  'Goodfellas',
						  'Back to the Future'],
				  'Joey': ['The Godfather',
						   'The Dark Knight',
						   'Pulp Fiction',
						   'Fight Club',
						   'Forrest Gump',
						   'Inception',
						   'Goodfellas',
						   'The Matrix',
						   'Interstellar',
						   'Raiders of the Lost Ark',
						   'Back to the Future',
						   'Logan',
						   'The Lion King',
						   'American Beauty',
						   'The Dark Knight Rises']}

NUM_MOVIES_WATCHED = {'Alex': 3,
					  'Tomer': 1,
					  'Matt': 1,
					  'Rachel': 1,
					  'Sam': 1,
					  'Joey': 3}